name: Matt Beaton
favicon: null
layout_spectrum: 0.5122542134486139
typography_spectrum: 0.51958456938155
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.37382919411174953
  lightness: 0.050435229670256376
  saturation: 0.6170801478438079
  rhythmicContrast: 0.6506551676429808
purpose: []
